export const breakfastFoods = [
    {
      id: 1,
      name: "Pancakes",
      description: "Fluffy pancakes served with syrup, butter, and fresh fruits.",
      actualPrice: 150,
      price: 120,
      type: "Veg",
      availableOn: ["Breakfast Delights", "Morning Glory", "Sunrise Cafe"],
      isAvailable: true,
      keywords: ["pancakes", "breakfast"],
      image: "https://i.ytimg.com/vi/RGHcYE-3j9s/maxresdefault.jpg",
    },
    {
      id: 2,
      name: "Omelette",
      description: "A classic omelette with cheese, tomatoes, and green peppers.",
      actualPrice: 100,
      price: 80,
      type: "Non-Veg",
      availableOn: ["Breakfast Delights", "Eggspectation", "Morning Glory"],
      isAvailable: true,
      keywords: ["omelette", "eggs"],
      image: "https://i.ytimg.com/vi/z3-mWz0p8gk/maxresdefault.jpg",
    },
    {
      id: 3,
      name: "French Toast",
      description: "Bread soaked in egg mixture and fried to golden perfection.",
      actualPrice: 130,
      price: 110,
      type: "Veg",
      availableOn: ["Sunrise Cafe", "Breakfast Bonanza", "Morning Glory"],
      isAvailable: true,
      keywords: ["french toast", "breakfast"],
      image: "https://i.ytimg.com/vi/Rb1zXnUYC1s/maxresdefault.jpg",
    },
    {
      id: 4,
      name: "Smoothie Bowl",
      description: "A refreshing smoothie bowl topped with granola and fruits.",
      actualPrice: 180,
      price: 160,
      type: "Veg",
      availableOn: ["Healthy Bites", "Morning Glory", "Sunrise Cafe"],
      isAvailable: true,
      keywords: ["smoothie", "healthy"],
      image: "https://i.ytimg.com/vi/ksnXZ2mDbnE/maxresdefault.jpg",
    },
    {
      id: 5,
      name: "Avocado Toast",
      description: "Toast topped with mashed avocado, salt, pepper, and lime.",
      actualPrice: 200,
      price: 180,
      type: "Veg",
      availableOn: ["Healthy Bites", "Sunrise Cafe", "Breakfast Delights"],
      isAvailable: true,
      keywords: ["avocado", "toast"],
      image: "https://i.ytimg.com/vi/6Av0U4AX7pU/maxresdefault.jpg",
    },
    {
      id: 6,
      name: "Breakfast Burrito",
      description: "A hearty burrito filled with eggs, cheese, and sausage.",
      actualPrice: 220,
      price: 200,
      type: "Non-Veg",
      availableOn: ["Breakfast Bonanza", "Eggspectation", "Morning Glory"],
      isAvailable: true,
      keywords: ["burrito", "breakfast"],
      image: "https://i.ytimg.com/vi/J3rLBE1oQA4/maxresdefault.jpg",
    },
    {
      id: 7,
      name: "Bagel with Cream Cheese",
      description: "A toasted bagel served with a generous spread of cream cheese.",
      actualPrice: 120,
      price: 100,
      type: "Veg",
      availableOn: ["Breakfast Bonanza", "Morning Glory", "Sunrise Cafe"],
      isAvailable: true,
      keywords: ["bagel", "cream cheese"],
      image: "https://i.ytimg.com/vi/RqztuY83GEc/maxresdefault.jpg",
    },
    {
      id: 8,
      name: "Granola Parfait",
      description: "Layers of granola, yogurt, and fresh fruits in a parfait glass.",
      actualPrice: 170,
      price: 150,
      type: "Veg",
      availableOn: ["Healthy Bites", "Sunrise Cafe", "Morning Glory"],
      isAvailable: true,
      keywords: ["granola", "parfait"],
      image: "https://i.ytimg.com/vi/DoK1N7Cy9mY/maxresdefault.jpg",
    },
    {
      id: 9,
      name: "Breakfast Sandwich",
      description: "A sandwich with egg, cheese, and bacon on a toasted bun.",
      actualPrice: 190,
      price: 170,
      type: "Non-Veg",
      availableOn: ["Breakfast Bonanza", "Eggspectation", "Sunrise Cafe"],
      isAvailable: true,
      keywords: ["sandwich", "breakfast"],
      image: "https://i.ytimg.com/vi/MfXzQ7h3hoE/maxresdefault.jpg",
    },
    {
      id: 10,
      name: "Fruit Salad",
      description: "A mix of fresh fruits served with a honey lime dressing.",
      actualPrice: 140,
      price: 120,
      type: "Veg",
      availableOn: ["Healthy Bites", "Morning Glory", "Sunrise Cafe"],
      isAvailable: true,
      keywords: ["fruit salad", "healthy"],
      image: "https://i.ytimg.com/vi/Vm25mGULSa4/maxresdefault.jpg",
    },
  ];
  