const dairyProducts = [
    {
      id: 1,
      name: "Milk",
      description: "Fresh and nutritious cow's milk.",
      actualPrice: 60,
      price: 50,
      type: "Dairy",
      availableOn: ["Dairy Farm", "Local Market", "SuperMart"],
      isAvailable: true,
      keywords: ["milk", "dairy"],
      image: "https://example.com/milk.jpg",
    },
    {
      id: 2,
      name: "Yogurt",
      description: "Creamy and delicious plain yogurt.",
      actualPrice: 100,
      price: 90,
      type: "Dairy",
      availableOn: ["Dairy Farm", "Healthy Bites", "SuperMart"],
      isAvailable: true,
      keywords: ["yogurt", "dairy"],
      image: "https://example.com/yogurt.jpg",
    },
    {
      id: 3,
      name: "Cheese",
      description: "Rich and flavorful cheddar cheese.",
      actualPrice: 150,
      price: 130,
      type: "Dairy",
      availableOn: ["Dairy Farm", "Cheese Delight", "SuperMart"],
      isAvailable: true,
      keywords: ["cheese", "dairy"],
      image: "https://example.com/cheese.jpg",
    },
    {
      id: 4,
      name: "Butter",
      description: "Creamy and smooth unsalted butter.",
      actualPrice: 120,
      price: 100,
      type: "Dairy",
      availableOn: ["Dairy Farm", "Local Market", "SuperMart"],
      isAvailable: true,
      keywords: ["butter", "dairy"],
      image: "https://example.com/butter.jpg",
    },
    {
      id: 5,
      name: "Cream",
      description: "Rich and thick fresh cream.",
      actualPrice: 140,
      price: 120,
      type: "Dairy",
      availableOn: ["Dairy Farm", "Healthy Bites", "SuperMart"],
      isAvailable: true,
      keywords: ["cream", "dairy"],
      image: "https://example.com/cream.jpg",
    },
    {
      id: 6,
      name: "Cottage Cheese",
      description: "Soft and fresh paneer made from cow's milk.",
      actualPrice: 200,
      price: 180,
      type: "Dairy",
      availableOn: ["Dairy Farm", "Cheese Delight", "SuperMart"],
      isAvailable: true,
      keywords: ["cottage cheese", "paneer"],
      image: "https://example.com/cottage_cheese.jpg",
    },
    {
      id: 7,
      name: "Ghee",
      description: "Pure and aromatic cow's ghee.",
      actualPrice: 300,
      price: 280,
      type: "Dairy",
      availableOn: ["Dairy Farm", "Local Market", "SuperMart"],
      isAvailable: true,
      keywords: ["ghee", "dairy"],
      image: "https://example.com/ghee.jpg",
    },
    {
      id: 8,
      name: "Whipped Cream",
      description: "Light and fluffy whipped cream.",
      actualPrice: 160,
      price: 140,
      type: "Dairy",
      availableOn: ["Dairy Farm", "Healthy Bites", "SuperMart"],
      isAvailable: true,
      keywords: ["whipped cream", "dairy"],
      image: "https://example.com/whipped_cream.jpg",
    },
    {
      id: 9,
      name: "Sour Cream",
      description: "Tangy and creamy sour cream.",
      actualPrice: 130,
      price: 110,
      type: "Dairy",
      availableOn: ["Dairy Farm", "Local Market", "SuperMart"],
      isAvailable: true,
      keywords: ["sour cream", "dairy"],
      image: "https://example.com/sour_cream.jpg",
    },
    {
      id: 10,
      name: "Ice Cream",
      description: "Delicious and creamy vanilla ice cream.",
      actualPrice: 250,
      price: 220,
      type: "Dairy",
      availableOn: ["Dairy Farm", "Ice Cream Parlor", "SuperMart"],
      isAvailable: true,
      keywords: ["ice cream", "dessert"],
      image: "https://example.com/ice_cream.jpg",
    },
  ];
  