const fruits = [
    {
      id: 1,
      name: "Apple",
      description: "Crisp and juicy red apples.",
      actualPrice: 120,
      price: 100,
      type: "Fruit",
      availableOn: ["Fresh Farm", "Local Market", "SuperMart"],
      isAvailable: true,
      keywords: ["apple", "fruit"],
      image: "https://example.com/apple.jpg",
    },
    {
      id: 2,
      name: "Banana",
      description: "Sweet and ripe bananas.",
      actualPrice: 60,
      price: 50,
      type: "Fruit",
      availableOn: ["Fresh Farm", "Local Market", "SuperMart"],
      isAvailable: true,
      keywords: ["banana", "fruit"],
      image: "https://example.com/banana.jpg",
    },
    {
      id: 3,
      name: "Orange",
      description: "Juicy and tangy oranges.",
      actualPrice: 80,
      price: 70,
      type: "Fruit",
      availableOn: ["Fresh Farm", "Citrus Grove", "SuperMart"],
      isAvailable: true,
      keywords: ["orange", "fruit"],
      image: "https://example.com/orange.jpg",
    },
    {
      id: 4,
      name: "Grapes",
      description: "Sweet and seedless green grapes.",
      actualPrice: 150,
      price: 130,
      type: "Fruit",
      availableOn: ["Fresh Farm", "Vineyard", "SuperMart"],
      isAvailable: true,
      keywords: ["grapes", "fruit"],
      image: "https://example.com/grapes.jpg",
    },
    {
      id: 5,
      name: "Strawberry",
      description: "Fresh and juicy strawberries.",
      actualPrice: 200,
      price: 180,
      type: "Fruit",
      availableOn: ["Fresh Farm", "Berry Fields", "SuperMart"],
      isAvailable: true,
      keywords: ["strawberry", "fruit"],
      image: "https://example.com/strawberry.jpg",
    },
    {
      id: 6,
      name: "Mango",
      description: "Sweet and tropical mangoes.",
      actualPrice: 250,
      price: 220,
      type: "Fruit",
      availableOn: ["Fresh Farm", "Tropical Paradise", "SuperMart"],
      isAvailable: true,
      keywords: ["mango", "fruit"],
      image: "https://example.com/mango.jpg",
    },
    {
      id: 7,
      name: "Pineapple",
      description: "Tropical and tangy pineapples.",
      actualPrice: 180,
      price: 160,
      type: "Fruit",
      availableOn: ["Fresh Farm", "Tropical Paradise", "SuperMart"],
      isAvailable: true,
      keywords: ["pineapple", "fruit"],
      image: "https://example.com/pineapple.jpg",
    },
    {
      id: 8,
      name: "Blueberry",
      description: "Sweet and nutritious blueberries.",
      actualPrice: 220,
      price: 200,
      type: "Fruit",
      availableOn: ["Fresh Farm", "Berry Fields", "SuperMart"],
      isAvailable: true,
      keywords: ["blueberry", "fruit"],
      image: "https://example.com/blueberry.jpg",
    },
    {
      id: 9,
      name: "Watermelon",
      description: "Refreshing and juicy watermelons.",
      actualPrice: 300,
      price: 250,
      type: "Fruit",
      availableOn: ["Fresh Farm", "Local Market", "SuperMart"],
      isAvailable: true,
      keywords: ["watermelon", "fruit"],
      image: "https://example.com/watermelon.jpg",
    },
    {
      id: 10,
      name: "Peach",
      description: "Sweet and fragrant peaches.",
      actualPrice: 190,
      price: 170,
      type: "Fruit",
      availableOn: ["Fresh Farm", "Orchard", "SuperMart"],
      isAvailable: true,
      keywords: ["peach", "fruit"],
      image: "https://example.com/peach.jpg",
    },
  ];
  