export const oilyFoods = [
  {
    id: 1,
    name: "Pizza",
    description:
      "A classic Italian dish made with dough, tomato sauce, cheese, and various toppings.",
    price: 200,
    actualPrice: 220,
    type: "Veg",
    availableOn: ["Gorkhyas fast food", "PartyFlow"],
    isAvailabe: true,
    keywords: ["pizza"],
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5tfnfSns3-dpInVOm3qrOGI_XqWKXp8NwvMOSXNFTc0ZqDZTzV-yRyqjgBk8DOe7ba0M&usqp=CAU",
  },
  {
    id: 2,
    name: "MOMO",
    description:
      "A classic Italian dish made with dough, tomato sauce, cheese, and various toppings.",
    actualPrice: 220,
    price: 200,
    type: "Veg",
    availableOn: ["Gorkhyas fast food", "PartyFlow"],
    isAvailabe: true,
    keywords: ["MOMO"],
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5tfnfSns3-dpInVOm3qrOGI_XqWKXp8NwvMOSXNFTc0ZqDZTzV-yRyqjgBk8DOe7ba0M&usqp=CAU",
  },
  {
    id: 3,
    name: "Chaumin",
    description:
      "A classic Italian dish made with dough, tomato sauce, cheese, and various toppings.",
    actualPrice: 220,
    price: 200,
    type: "Chicken",
    availableOn: ["Gorkhyas fast food", "PartyFlow", "cocobew"],
    isAvailabe: true,
    keywords: ["chaumin"],
    image: "https://i.ytimg.com/vi/w8dDtaN389M/maxresdefault.jpg",
  },
  {
    id: 4,
    name: "Burger",
    description:
      "A classic Italian dish made with dough, tomato sauce, cheese, and various toppings.",
    actualPrice: 220,
    price: 200,
    type: "Veg",
    availableOn: ["Gorkhyas fast food", "PartyFlow", "cocobew"],
    isAvailabe: true,
    keywords: ["chaumin"],
    image: "https://i.ytimg.com/vi/w8dDtaN389M/maxresdefault.jpg",
  },
  {
    id: 5,
    name: "Burger",
    description:
      "A classic Italian dish made with dough, tomato sauce, cheese, and various toppings.",
    price: 200,
    actualPrice: 220,
    type: "Veg",
    availableOn: ["Gorkhyas fast food", "PartyFlow", "cocobew"],
    isAvailabe: true,
    keywords: ["chaumin"],
    image: "https://i.ytimg.com/vi/w8dDtaN389M/maxresdefault.jpg",
  },
  {
    id: 6,
    name: "Chaumin",
    description:
      "A classic Italian dish made with dough, tomato sauce, cheese, and various toppings.",
    actualPrice: 220,
    price: 200,
    type: "Veg",
    availableOn: ["Gorkhyas fast food", "PartyFlow", "cocobew"],
    isAvailabe: true,
    keywords: ["chaumin"],
    image: "https://i.ytimg.com/vi/w8dDtaN389M/maxresdefault.jpg",
  },
  {
    id: 7,
    name: "Burger",
    description:
      "A classic Italian dish made with dough, tomato sauce, cheese, and various toppings.",
    actualPrice: 220,
    price: 200,
    type: "Veg",
    availableOn: ["Gorkhyas fast food", "PartyFlow", "cocobew"],
    isAvailabe: true,
    keywords: ["chaumin"],
    image: "https://i.ytimg.com/vi/w8dDtaN389M/maxresdefault.jpg",
  },
  {
    id: 8,
    name: "Burger",
    description:
      "A classic Italian dish made with dough, tomato sauce, cheese, and various toppings.",
    price: 200,
    actualPrice: 220,
    type: "Veg",
    availableOn: ["Gorkhyas fast food", "PartyFlow", "cocobew"],
    isAvailabe: true,
    keywords: ["chaumin"],
    image: "https://i.ytimg.com/vi/w8dDtaN389M/maxresdefault.jpg",
  },
  {
    id: 9,
    name: "Burger",
    description:
      "A classic Italian dish made with dough, tomato sauce, cheese, and various toppings.",
    price: 200,
    actualPrice: 220,
    type: "Veg",
    availableOn: ["Gorkhyas fast food", "PartyFlow", "cocobew"],
    isAvailabe: true,
    keywords: ["chaumin"],
    image: "https://i.ytimg.com/vi/w8dDtaN389M/maxresdefault.jpg",
  },
  {
    id: 10,
    name: "Chaumin",
    description:
      "A classic Italian dish made with dough, tomato sauce, cheese, and various toppings.",
    actualPrice: 220,
    price: 200,
    type: "Veg",
    availableOn: ["Gorkhyas fast food", "PartyFlow", "cocobew"],
    isAvailabe: true,
    keywords: ["chaumin"],
    image: "https://i.ytimg.com/vi/w8dDtaN389M/maxresdefault.jpg",
  },
  {
    id: 11,
    name: "Burger",
    description:
      "A classic Italian dish made with dough, tomato sauce, cheese, and various toppings.",
    actualPrice: 220,
    price: 200,
    type: "Veg",
    availableOn: ["Gorkhyas fast food", "PartyFlow", "cocobew"],
    isAvailabe: true,
    keywords: ["chaumin"],
    image: "https://i.ytimg.com/vi/w8dDtaN389M/maxresdefault.jpg",
  },
  {
    id: 12,
    name: "Burger",
    description:
      "A classic Italian dish made with dough, tomato sauce, cheese, and various toppings.",
    price: 200,
    actualPrice: 220,
    type: "Veg",
    availableOn: ["Gorkhyas fast food", "PartyFlow", "cocobew"],
    isAvailabe: true,
    keywords: ["chaumin"],
    image: "https://i.ytimg.com/vi/w8dDtaN389M/maxresdefault.jpg",
  },
  {
    id: 13,
    name: "Chaumin",
    description:
      "A classic Italian dish made with dough, tomato sauce, cheese, and various toppings.",
    actualPrice: 220,
    price: 200,
    type: "Veg",
    availableOn: ["Gorkhyas fast food", "PartyFlow", "cocobew"],
    isAvailabe: true,
    keywords: ["chaumin"],
    image: "https://i.ytimg.com/vi/w8dDtaN389M/maxresdefault.jpg",
  },
  {
    id: 14,
    name: "Burger",
    description:
      "A classic Italian dish made with dough, tomato sauce, cheese, and various toppings.",
    actualPrice: 220,
    price: 200,
    type: "Veg",
    availableOn: ["Gorkhyas fast food", "PartyFlow", "cocobew"],
    isAvailabe: true,
    keywords: ["chaumin"],
    image: "https://i.ytimg.com/vi/w8dDtaN389M/maxresdefault.jpg",
  },
  {
    id: 15,
    name: "Burger",
    description:
      "A classic Italian dish made with dough, tomato sauce, cheese, and various toppings.",
    price: 200,
    actualPrice: 220,
    type: "Veg",
    availableOn: ["Gorkhyas fast food", "PartyFlow", "cocobew"],
    isAvailabe: true,
    keywords: ["chaumin"],
    image: "https://i.ytimg.com/vi/w8dDtaN389M/maxresdefault.jpg",
  },
];
